#:kivy 2.1.0
#:import hex kivy.utils.get_color_from_hex

<StartingScreen>:
    bl1: testBoxLayout

    GridLayout:
        cols: 2
        rows: 1
        spacing: 1

        ScrollView:
            id: svScrollBar2
            do_scroll_x: False
            do_scroll_y: True
            effect_cls: 'ScrollEffect'
            size_hint_x: None
            width: 100
            
            BoxLayout:
                id: testBoxLayout
                orientation: "vertical"
                size_hint_y: None
                height: self.minimum_height
                spacing: 1

        ScrollView:
            id: svScrollBar
            # effect_cls: 'ScrollEffect'
            
            BoxLayout:
                id: boxLayoutPost
                orientation: 'vertical'
                size_hint_y: None
                height: self.minimum_height
                spacing: 2
                padding: 40, 0 # left, top
                
                Label:
                    id: category1
                    size_hint_y: None
                    size_hint_x: None
                    height: 49
                    width: 700
                    text: ""
                    disabled: False
                    opacity: 1
                    halign: 'center'
                    color: "white"
                    bold: True,
                    opacity: 0.9
                    font_size: 16

                BoxLayout:
                    id: boxLayoutNewsCard1
                    orientation: 'horizontal'
                    size_hint_y: None
                    size_hint_x: None
                    height: self.minimum_height
                    width: 700
                    spacing: 0
                    padding: 0
                    opacity: 0
                    disabled: False
                    
                    #creating canvas
                    canvas.before:
                        Color:
                            rgba: hex('#0e1012') # #1DA1F2 # 0, 0, 1, 1  # hex('#0e1012') # Blue
                        Rectangle:
                            pos: self.pos
                            size: self.width, self.height #width, height
                    Label:
                        id: newsCard1Post
                        size_hint_y: None
                        size_hint_x: None
                        text: ""
                        padding: 40, 20 #left, top
                        text_size: 660, 240 #width, height
                        height: 240
                        width: 640
                        multiline: True
                        disabled: False
                        halign:'left'
                        valign: 'top'
                        color: 'white'
                        opacity: 0.9
                        font_size: 16
                        disabled: False
                        bold: True
                        # height: self.texture_size[1]
                        # text_size: self.width, None
                        # size: self.texture_size
                    StackLayout:
                        orientation: 'tb-lr'
                        size_hint_y: 1
                        size_hint_x: None
                        width: 36
                        spacing: 0
                        padding: 0
                        # padding: 0, 70 #left, top
                        Label:
                            id: buttonCopyLink
                            size_hint_y: None
                            size_hint_x: None
                            height: 49
                            width: 60
                            text: "§"
                            background_color: "#292f33"
                            disabled: False
                            opacity: 1
                            on_touch_down: root.copyToClipboard(newsCard1Post.type) if self.collide_point(*args[1].pos) else False
                            valign: 'top'
                            color: "white"
                            bold: True
                            font_size: 16
                        Label:
                            id: buttonAddToFavs
                            size_hint_y: None
                            size_hint_x: None
                            height: 40
                            width: 60
                            text: "+"
                            background_color: "#292f33"
                            disabled: False
                            opacity: 1 
                            on_touch_down: root.saveToFavorites(self, newsCard1Post.type) if self.collide_point(*args[1].pos) else False
                            valign: 'top'
                            color: "white"
                            bold: True
                            font_size: 19
                        Label:
                            id: buttonPreviousPost
                            size_hint_y: None
                            size_hint_x: None
                            height: 40
                            width: 60
                            text: "<"
                            background_color: "#292f33"
                            disabled: False
                            opacity: 1 
                            on_touch_down: root.previousPost(newsCard1Post.order, newsCard1Post.type) if self.collide_point(*args[1].pos) else False
                            valign: 'top'
                            color: "white"
                            bold: True
                            font_size: 19
                        Label:
                            id: buttonNextPost
                            size_hint_y: None
                            size_hint_x: None
                            height: 40
                            width: 60
                            text: ">"
                            background_color: "#292f33"
                            disabled: False
                            opacity: 1 
                            on_touch_down: root.nextPost(newsCard1Post.order, newsCard1Post.type) if self.collide_point(*args[1].pos) else False
                            valign: 'top'
                            color: "white"
                            bold: True
                            font_size: 19

                Label:
                    id: category2
                    size_hint_y: None
                    size_hint_x: None
                    height: 49
                    width: 700
                    text: ""
                    disabled: False
                    opacity: 1
                    halign: 'center'
                    color: "white"
                    bold: True,
                    opacity: 0.9
                    font_size: 16

                BoxLayout:
                    id: boxLayoutNewsCard2
                    orientation: 'horizontal'
                    size_hint_y: None
                    size_hint_x: None
                    height: self.minimum_height
                    width: 700
                    spacing: 0
                    padding: 0
                    opacity: 0
                    disabled: False
                    
                    canvas.before:
                        Color:
                            rgba: hex('#0e1012') # FF0000 # 0, 0, 1, 1  # hex('#0e1012') # Blue
                        Rectangle:
                            pos: self.pos
                            size: self.width, self.height #width, height
                    Label:
                        id: newsCard2Post
                        size_hint_y: None
                        size_hint_x: None
                        text: ""
                        padding: 40, 20 #left, top
                        text_size: 660, 240 #width, height
                        height: 240
                        width: 640
                        multiline: True
                        disabled: False
                        halign:'left'
                        valign: 'top'
                        color: 'white'
                        opacity: 0.9
                        font_size: 16
                        disabled: False
                        bold: True
                        # height: self.texture_size[1]
                        # size: self.texture_size
                        # text_size: self.width, None
                        # background_color: '#1DA1F2' # 292f33
                    StackLayout:
                        orientation: 'tb-lr'
                        size_hint_y: 1
                        size_hint_x: None
                        width: 36
                        spacing: 0
                        padding: 0
                        # padding: 0, 70 #left, top
                        Label:
                            id: buttonCopyLink
                            size_hint_y: None
                            size_hint_x: None
                            height: 49
                            width: 60
                            text: "§"
                            background_color: "#292f33"
                            disabled: False
                            opacity: 1
                            on_touch_down: root.copyToClipboard(newsCard2Post.type) if self.collide_point(*args[1].pos) else False
                            valign: 'top'
                            color: "white"
                            bold: True
                            font_size: 16
                        Label:
                            id: buttonAddToFavs
                            size_hint_y: None
                            size_hint_x: None
                            height: 40
                            width: 60
                            text: "+"
                            background_color: "#292f33"
                            disabled: False
                            opacity: 1 
                            on_touch_down: root.saveToFavorites(self, newsCard2Post.type) if self.collide_point(*args[1].pos) else False
                            valign: 'top'
                            color: "white"
                            bold: True
                            font_size: 19
                        Label:
                            id: buttonPreviousPost
                            size_hint_y: None
                            size_hint_x: None
                            height: 40
                            width: 60
                            text: "<"
                            background_color: "#292f33"
                            disabled: False
                            opacity: 1 
                            on_touch_down: root.previousPost(newsCard2Post.order, newsCard2Post.type) if self.collide_point(*args[1].pos) else False
                            valign: 'top'
                            color: "white"
                            bold: True
                            font_size: 19
                        Label:
                            id: buttonNextPost
                            size_hint_y: None
                            size_hint_x: None
                            height: 40
                            width: 60
                            text: ">"
                            background_color: "#292f33"
                            disabled: False
                            opacity: 1 
                            on_touch_down: root.nextPost(newsCard2Post.order, newsCard2Post.type) if self.collide_point(*args[1].pos) else False
                            valign: 'top'
                            color: "white"
                            bold: True
                            font_size: 19

                Label:
                    id: category3
                    size_hint_y: None
                    size_hint_x: None
                    height: 49
                    width: 700
                    text: ""
                    disabled: False
                    opacity: 1
                    halign: 'center'
                    color: "white"
                    bold: True,
                    opacity: 0.9
                    font_size: 16

                BoxLayout:
                    id: boxLayoutNewsCard3
                    orientation: 'horizontal'
                    size_hint_y: None
                    size_hint_x: None
                    height: self.minimum_height
                    width: 700
                    spacing: 0
                    padding: 0
                    opacity: 0
                    disabled: False
                    
                    canvas.before:
                        Color:
                            rgba: hex('#0e1012') # FF0000 # 0, 0, 1, 1  # hex('#0e1012') # Blue
                        Rectangle:
                            pos: self.pos
                            size: self.width, self.height #width, height
                    Label:
                        id: newsCard3Post
                        size_hint_y: None
                        size_hint_x: None
                        text: ""
                        padding: 40, 20 #left, top
                        text_size: 660, 240 #width, height
                        height: 240
                        width: 640
                        multiline: True
                        disabled: False
                        halign:'left'
                        valign: 'top'
                        color: 'white'
                        opacity: 0.9
                        font_size: 16
                        disabled: False
                        bold: True
                        # height: self.texture_size[1]
                        # size: self.texture_size
                        # text_size: self.width, None
                        # background_color: '#1DA1F2' # 292f33
                    StackLayout:
                        orientation: 'tb-lr'
                        size_hint_y: 1
                        size_hint_x: None
                        width: 36
                        spacing: 0
                        padding: 0
                        # padding: 0, 70 #left, top
                        Label:
                            id: buttonCopyLink
                            size_hint_y: None
                            size_hint_x: None
                            height: 49
                            width: 60
                            text: "§"
                            background_color: "#292f33"
                            disabled: False
                            opacity: 1
                            on_touch_down: root.copyToClipboard(newsCard3Post.type) if self.collide_point(*args[1].pos) else False
                            valign: 'top'
                            color: "white"
                            bold: True
                            font_size: 16
                        Label:
                            id: buttonAddToFavs
                            size_hint_y: None
                            size_hint_x: None
                            height: 40
                            width: 60
                            text: "+"
                            background_color: "#292f33"
                            disabled: False
                            opacity: 1 
                            on_touch_down: root.saveToFavorites(self, newsCard3Post.type) if self.collide_point(*args[1].pos) else False
                            valign: 'top'
                            color: "white"
                            bold: True
                            font_size: 19
                        Label:
                            id: buttonPreviousPost
                            size_hint_y: None
                            size_hint_x: None
                            height: 40
                            width: 60
                            text: "<"
                            background_color: "#292f33"
                            disabled: False
                            opacity: 1 
                            on_touch_down: root.previousPost(newsCard3Post.order, newsCard3Post.type) if self.collide_point(*args[1].pos) else False
                            valign: 'top'
                            color: "white"
                            bold: True
                            font_size: 19
                        Label:
                            id: buttonNextPost
                            size_hint_y: None
                            size_hint_x: None
                            height: 40
                            width: 60
                            text: ">"
                            background_color: "#292f33"
                            disabled: False
                            opacity: 1 
                            on_touch_down: root.nextPost(newsCard3Post.order, newsCard3Post.type) if self.collide_point(*args[1].pos) else False
                            valign: 'top'
                            color: "white"
                            bold: True
                            font_size: 19

                Label:
                    id: category4
                    size_hint_y: None
                    size_hint_x: None
                    height: 49
                    width: 700
                    text: ""
                    disabled: False
                    opacity: 1
                    halign: 'center'
                    color: "white"
                    bold: True,
                    opacity: 0.9
                    font_size: 16

<AddProfileScreen>:
    bl2: testBoxLayout
    ti1: profileName
    ti2: profileYoutube
    ti3: profileTwitter
    ti4: profileArticles
    ti5: profileSubreddit
    
    GridLayout:
        cols: 2
        rows: 1

        ScrollView:
            id: svScrollBar2
            do_scroll_x: False
            do_scroll_y: True
            effect_cls: 'ScrollEffect'
            size_hint_x: None
            width: 100

            BoxLayout:
                id: testBoxLayout
                orientation: "vertical"
                size_hint_y: None
                height: self.minimum_height
                Button:
                    size_hint_y: None
                    text: "<"
                    on_press: root.manager.current = 'start'
                    font_size: 40
                    disabled: False
                    background_color: "black"

        StackLayout:
            id: testStackLayout1
            size_hint_y: 1
            size_hint_x: 1
            
            Label:
                size_hint_y: None
                size_hint_x: 1
                height: 40
                text: "Custom Profile"
            TextInput:
                id: profileName
                size_hint_y: None
                size_hint_x: 1
                height: 40
                # width: 700
                font_size: 20
                hint_text: "profile name"
                halign: "center"
            TextInput:
                id: profileYoutube
                size_hint_y: None
                size_hint_x: 1
                height: 40
                # width: 700
                font_size: 20
                hint_text: "youtube channel"
                halign: "center"
            TextInput:
                id: profileTwitter
                size_hint_y: None
                size_hint_x: 1
                height: 40
                # width: 700
                font_size: 20
                hint_text: "twitter username"
                halign: "center"
            TextInput:
                id: profileArticles
                size_hint_y: None
                size_hint_x: 1
                height: 40
                # width: 700
                font_size: 20
                hint_text: "search phrase for articles"
                halign: "center"
            TextInput:
                id: profileSubreddit
                size_hint_y: None
                size_hint_x: 1
                height: 40
                # width: 700
                font_size: 20
                hint_text: "subreddit"
                halign: "center"
            # TextInput:
            #     id: profileFillter
            #     size_hint_y: None
            #     size_hint_x: None
                # height: 40
                # width: 700
                # disabled: True
            Button:
                size_hint_y: None
                size_hint_x: 1
                height: 40
                # width: 700
                text: "Add"
                background_color: 'lightgreen'
                on_press: root.fetch_profile_inputs()
            Label:
                size_hint_y: None
                size_hint_x: 1
                height: 40
                text: "Newssites"
            Button:
                size_hint_y: None
                size_hint_x: 1
                height: 40
                # width: 700
                text: "Add Newssite #1"
                background_color: 'lightgreen'
                on_press: 
            Button:
                size_hint_y: None
                size_hint_x: 1
                height: 40
                # width: 700
                text: "Add Newssite #2"
                background_color: 'lightgreen'
                on_press: 
            Button:
                size_hint_y: None
                size_hint_x: 1
                height: 40
                # width: 700
                text: "Add Newssite #3"
                background_color: 'lightgreen'
                on_press: 

<EditProfileScreen>:
    bl2: testBoxLayout
    bl3: testBoxLayout2
    st1: testStackLayout1
    ti1: profileName
    
    GridLayout:
        cols: 2
        rows: 1

        ScrollView:
            id: svScrollBar1
            do_scroll_x: False
            do_scroll_y: True
            effect_cls: 'ScrollEffect'
            size_hint_x: None
            width: 100

            BoxLayout:
                id: testBoxLayout
                orientation: "vertical"
                size_hint_y: None
                height: self.minimum_height

                Button:
                    size_hint_y: None
                    text: "<"
                    on_press: root.manager.current = 'start'
                    font_size: 40
                    disabled: False
                    background_color: "black"

        StackLayout:
            id: testStackLayout1
            size_hint_y: 1
            size_hint_x: 1

            # Label:
            #     size_hint_y: None
            #     size_hint_x: 1
            #     height: 40
            #     text: "Delete Profile"
            TextInput:
                id: profileName
                size_hint_y: None
                size_hint_x: 1
                height: 40
                font_size: 20
                hint_text: "Select Profile"
                halign: "center"
                disabled: True

            # Label:
            #     size_hint_y: None
            #     size_hint_x: 1
            #     height: 40
            #     text: "All Profiles"

            ScrollView:
                id: svScrollBar2
                do_scroll_x: False
                do_scroll_y: True
                effect_cls: 'ScrollEffect'
                size_hint_y: None
                size_hint_x: 1
                height: 440 + 80

                BoxLayout:
                    id: testBoxLayout2
                    orientation: 'vertical'
                    size_hint_y: None
                    height: self.minimum_height

            Button:
                size_hint_y: None
                size_hint_x: 1
                height: 40
                background_color: 'red'
                text: "Remove"
                on_press: root.DeleteProfile()

<FavoritesScreen>:
    bl2: testBoxLayout
    
    GridLayout:
        cols: 2
        rows: 1

        ScrollView:
            id: svScrollBar2
            do_scroll_x: False
            do_scroll_y: True
            effect_cls: 'ScrollEffect'
            size_hint_x: None
            width: 100

            BoxLayout:
                id: testBoxLayout
                orientation: "vertical"
                size_hint_y: None
                height: self.minimum_height
                Button:
                    size_hint_y: None
                    text: "<"
                    on_press: root.manager.current = 'start'
                    font_size: 40
                    disabled: False
                    background_color: "black"
        
        ScrollView:
            id: svScrollBar
            effect_cls: 'ScrollEffect'
            
            BoxLayout:
                id: boxLayoutPost
                orientation: 'vertical'
                size_hint_y: None
                height: self.minimum_height
                spacing: 10
                padding: 10

<BlankScreen>: