#:kivy 2.0.0
#:import hex kivy.utils.get_color_from_hex


#Screen 1: News Feed
<NewsFeedScreen>:
    bl1: boxLayout1

    GridLayout:
        cols: 2
        rows: 1
        spacing: 1

        ScrollView:
            id: svScrollBar2
            do_scroll_x: False
            do_scroll_y: True
            effect_cls: 'ScrollEffect'
            size_hint_x: None
            width: 100
            
            BoxLayout:
                id: boxLayout1
                orientation: "vertical"
                size_hint_y: None
                height: self.minimum_height
                spacing: 1

        ScrollView:
            id: svScrollBar
            effect_cls: 'ScrollEffect'

            BoxLayout:
                id: boxLayoutPost
                orientation: 'vertical'
                size_hint_y: None
                height: self.minimum_height
                spacing: 2
                padding: 40, 0 # left, top

                Label:
                    id: category1
                    size_hint_y: None
                    size_hint_x: None
                    height: 80
                    width: 730
                    text: ""
                    disabled: False
                    opacity: 1
                    halign: 'left'
                    color: "white"
                    bold: True,
                    opacity: 1
                    font_size: 21

                BoxLayout:
                    id: boxLayoutNewsCard1
                    orientation: 'horizontal'
                    size_hint_y: None
                    size_hint_x: None
                    height: self.minimum_height
                    width: 730
                    spacing: 0
                    padding: 0
                    opacity: 0
                    disabled: False
                    
                    Button:
                        id: buttonLeftSideFiller1
                        size_hint_y: 1
                        size_hint_x: None
                        height: 100
                        width: 40
                        text: ""
                        # background_color: hex('#1DA1F2') # "white" # hex('#1DA1F2') # "darkgray" # "#292f33"
                        background_normal: "transparent"
                        background_down: "transparent"
                        disabled: False
                        opacity: 1
                        valign: 'top'
                        color: "white"
                        bold: False
                        font_size: 16 
                    Button:
                        id: newsCard1Post
                        size_hint_y: None
                        size_hint_x: None
                        text: ""
                        padding: 10, 20 #left, top
                        text_size: self.width, None #width, height
                        height: self.texture_size[1]
                        width: 730
                        multiline: True
                        disabled: False
                        halign:'left'
                        valign: 'top'
                        color: 'white'
                        opacity: 1
                        font_size: 17
                        disabled: False
                        bold: True
                        on_touch_down: root.next_post(newsCard1Post.order, newsCard1Post.type) if self.collide_point(*args[1].pos) else False
                        background_color: hex('#0e1012')
                        background_normal: "transparent"
                        background_down: "transparent"
                        # height: self.texture_size[1]
                        # text_size: self.width, None
                        # size: self.texture_size
                    
                    BoxLayout:
                        id: boxLayoutVerticalRightSide1
                        orientation: 'vertical'
                        # size_hint_y: None
                        # size_hint_x: None
                        # height: self.minimum_height
                        # width: 730
                        # spacing: 0
                        # padding: 0
                        # opacity: 0
                        disabled: False
                        
                        Button:
                            id: buttonAddToFavs1
                            size_hint_y: 1
                            size_hint_x: None
                            height: 100
                            width: 46
                            text: "~"
                            background_color: hex('#0e1012') # "green" # "#292f33"
                            background_normal: "transparent" # "#292f33"
                            background_down: "transparent" # "#292f33"
                            disabled: False
                            opacity: 1
                            on_touch_down: root.favorites_save(self, newsCard1Post.type) if self.collide_point(*args[1].pos) else False
                            valign: 'top'
                            color: "white"
                            bold: False
                            font_size: 19
                        Button:
                            id: buttonCopyLink1
                            size_hint_y: 1
                            size_hint_x: None
                            height: 100
                            width: 46
                            text: "§"
                            background_color: hex('#0e1012') # "white" # hex('#1DA1F2') # "darkgray" # "#292f33"
                            background_normal: "transparent"
                            background_down: "transparent"
                            disabled: False
                            opacity: 1
                            on_touch_down: root.copy_to_clipboard(newsCard1Post.type) if self.collide_point(*args[1].pos) else False
                            valign: 'top'
                            color: "white"
                            bold: False
                            font_size: 16 

                Label:
                    id: category2
                    size_hint_y: None
                    size_hint_x: None
                    height: 1
                    width: 730
                    text: ""
                    disabled: False
                    opacity: 1
                    halign: 'center'
                    color: "white"
                    bold: True,
                    opacity: 0.9
                    font_size: 16

                BoxLayout:
                    id: boxLayoutNewsCard2
                    orientation: 'horizontal'
                    size_hint_y: None
                    size_hint_x: None
                    height: self.minimum_height
                    width: 730
                    spacing: 0
                    padding: 0
                    opacity: 0
                    disabled: False
                    
                    Button:
                        id: buttonLeftSideFiller2
                        size_hint_y: 1
                        size_hint_x: None
                        height: 100
                        width: 40
                        text: ""
                        # background_color: hex('#1DA1F2') # "white" # hex('#1DA1F2') # "darkgray" # "#292f33"
                        background_normal: "transparent"
                        background_down: "transparent"
                        disabled: False
                        opacity: 1
                        valign: 'top'
                        color: "white"
                        bold: False
                    Button:
                        id: newsCard2Post
                        size_hint_y: None
                        size_hint_x: None
                        text: ""
                        padding: 10, 20 #left, top
                        # text_size: 660, 240 #width, height
                        # height: 240
                        text_size: self.width, None #width, height
                        height: self.texture_size[1]
                        width: 730
                        multiline: True
                        disabled: False
                        halign:'left'
                        valign: 'top'
                        color: 'white'
                        opacity: 1
                        font_size: 17
                        disabled: False
                        bold: True
                        on_touch_down: root.next_post(newsCard2Post.order, newsCard2Post.type) if self.collide_point(*args[1].pos) else False
                        background_color: hex('#0e1012')
                        background_normal: "transparent"
                        background_down: "transparent"
                        # height: self.texture_size[1]
                        # size: self.texture_size
                        # text_size: self.width, None
                        # background_color: '#1DA1F2' # 292f33
                    
                    BoxLayout:
                        id: boxLayoutVerticalRightSide2
                        orientation: 'vertical'
                        # size_hint_y: None
                        # size_hint_x: None
                        # height: self.minimum_height
                        # width: 730
                        # spacing: 0
                        # padding: 0
                        # opacity: 0
                        disabled: False
                        
                        Button:
                            id: buttonAddToFavs2
                            size_hint_y: 1
                            size_hint_x: None
                            height: 100
                            width: 46
                            text: "~"
                            background_color: hex('#0e1012') # "green" # "#292f33"
                            background_normal: "transparent" # "#292f33"
                            background_down: "transparent" # "#292f33"
                            disabled: False
                            opacity: 1 
                            on_touch_down: root.favorites_save(self, newsCard2Post.type) if self.collide_point(*args[1].pos) else False
                            valign: 'top'
                            color: "white"
                            bold: False
                            font_size: 19
                        Button:
                            id: buttonCopyLink2
                            size_hint_y: 1
                            size_hint_x: None
                            height: 100
                            width: 46
                            text: "§"
                            background_color: hex('#0e1012') # "white" # hex('#1DA1F2') # "darkgray" # "#292f33"
                            background_normal: "transparent"
                            background_down: "transparent"
                            disabled: False
                            opacity: 1
                            on_touch_down: root.copy_to_clipboard(newsCard2Post.type) if self.collide_point(*args[1].pos) else False
                            valign: 'top'
                            color: "white"
                            bold: False
                            font_size: 16 

                Label:
                    id: category3
                    size_hint_y: None
                    size_hint_x: None
                    height: 1
                    width: 730
                    text: ""
                    disabled: False
                    opacity: 1
                    halign: 'center'
                    color: "white"
                    bold: True,
                    opacity: 1
                    font_size: 16

                BoxLayout:
                    id: boxLayoutNewsCard3
                    orientation: 'horizontal'
                    size_hint_y: None
                    size_hint_x: None
                    height: self.minimum_height
                    width: 730
                    spacing: 0
                    padding: 0
                    opacity: 0
                    disabled: False
                                        
                    Button:
                        id: buttonLeftSideFiller3
                        size_hint_y: 1
                        size_hint_x: None
                        height: 100
                        width: 40
                        text: ""
                        # background_color: hex('#1DA1F2') # "white" # hex('#1DA1F2') # "darkgray" # "#292f33"
                        background_normal: "transparent"
                        background_down: "transparent"
                        disabled: False
                        opacity: 1
                        valign: 'top'
                        color: "white"
                        bold: False
                    Button:
                        id: newsCard3Post
                        size_hint_y: None
                        size_hint_x: None
                        text: ""
                        padding: 10, 20 #left, top
                        # text_size: 660, 240 #width, height
                        # height: 240
                        text_size: self.width, None #width, height
                        height: self.texture_size[1]
                        width: 730
                        multiline: True
                        disabled: False
                        halign:'left'
                        valign: 'top'
                        color: 'white'
                        opacity: 1
                        font_size: 17
                        disabled: False
                        bold: True
                        on_touch_down: root.next_post(newsCard3Post.order, newsCard3Post.type) if self.collide_point(*args[1].pos) else False
                        background_color: hex('#0e1012')
                        background_normal: "transparent"
                        background_down: "transparent"
                        # height: self.texture_size[1]
                        # size: self.texture_size
                        # text_size: self.width, None
                        # background_color: '#1DA1F2' # 292f33
                    
                    BoxLayout:
                        id: boxLayoutVerticalRightSide3
                        orientation: 'vertical'
                        # size_hint_y: None
                        # size_hint_x: None
                        # height: self.minimum_height
                        # width: 730
                        # spacing: 0
                        # padding: 0
                        # opacity: 0
                        disabled: False
                        
                        Button:
                            id: buttonAddToFavs3
                            size_hint_y: 1
                            size_hint_x: None
                            height: 100
                            width: 46
                            text: "~"
                            background_color: hex('#0e1012') # "green" # "#292f33"
                            background_normal: "transparent" # "#292f33"
                            background_down: "transparent" # "#292f33"
                            disabled: False
                            opacity: 1 
                            on_touch_down: root.favorites_save(self, newsCard3Post.type) if self.collide_point(*args[1].pos) else False
                            valign: 'top'
                            color: "white"
                            bold: False
                            font_size: 19
                        Button:
                            id: buttonCopyLink3
                            size_hint_y: 1
                            size_hint_x: None
                            height: 100
                            width: 46
                            text: "§"
                            background_color: hex('#0e1012') # "white" # hex('#1DA1F2') # "darkgray" # "#292f33"
                            background_normal: "transparent"
                            background_down: "transparent"
                            disabled: False
                            opacity: 1
                            on_touch_down: root.copy_to_clipboard(newsCard3Post.type) if self.collide_point(*args[1].pos) else False
                            valign: 'top'
                            color: "white"
                            bold: False
                            font_size: 16 

                Label:
                    id: category4
                    size_hint_y: None
                    size_hint_x: None
                    height: 1
                    width: 730
                    text: ""
                    disabled: False
                    opacity: 1
                    halign: 'center'
                    color: "white"
                    bold: True,
                    opacity: 1
                    font_size: 16

                BoxLayout:
                    id: boxLayoutNewsCard4
                    orientation: 'horizontal'
                    size_hint_y: None
                    size_hint_x: None
                    height: self.minimum_height
                    width: 730
                    spacing: 0
                    padding: 0
                    opacity: 0
                    disabled: False

                    Button:
                        id: buttonLeftSideFiller4
                        size_hint_y: 1
                        size_hint_x: None
                        height: 100
                        width: 40
                        text: ""
                        # background_color: hex('#1DA1F2') # "white" # hex('#1DA1F2') # "darkgray" # "#292f33"
                        background_normal: "transparent"
                        background_down: "transparent"
                        disabled: False
                        opacity: 1
                        valign: 'top'
                        color: "white"
                        bold: False
                    Button:
                        id: newsCard4Post
                        size_hint_y: None
                        size_hint_x: None
                        text: ""
                        padding: 10, 20 #left, top
                        # text_size: 660, 240 #width, height
                        # height: 240
                        text_size: self.width, None #width, height
                        height: self.texture_size[1]
                        width: 730
                        multiline: True
                        disabled: False
                        halign:'left'
                        valign: 'top'
                        color: 'white'
                        opacity: 1
                        font_size: 17
                        disabled: False
                        bold: True
                        on_touch_down: root.next_post(newsCard4Post.order, newsCard4Post.type) if self.collide_point(*args[1].pos) else False
                        background_color: hex('#0e1012')
                        background_normal: "transparent"
                        background_down: "transparent"
                        # height: self.texture_size[1]
                        # size: self.texture_size
                        # text_size: self.width, None
                        # background_color: '#1DA1F2' # 292f33
                    
                    BoxLayout:
                        id: boxLayoutVerticalRightSide4
                        orientation: 'vertical'
                        # size_hint_y: None
                        # size_hint_x: None
                        # height: self.minimum_height
                        # width: 730
                        # spacing: 0
                        # padding: 0
                        # opacity: 0
                        disabled: False
                        
                        Button:
                            id: buttonAddToFavs4
                            size_hint_y: 1
                            size_hint_x: None
                            height: 100
                            width: 46
                            text: "~"
                            background_color: hex('#0e1012') # "green" # "#292f33"
                            background_normal: "transparent" # "#292f33"
                            background_down: "transparent" # "#292f33"
                            disabled: False
                            opacity: 1 
                            on_touch_down: root.favorites_save(self, newsCard4Post.type) if self.collide_point(*args[1].pos) else False
                            valign: 'top'
                            color: "white"
                            bold: False
                            font_size: 19
                        Button:
                            id: buttonCopyLink4
                            size_hint_y: 1
                            size_hint_x: None
                            height: 100
                            width: 46
                            text: "§"
                            background_color: hex('#0e1012') # "white" # hex('#1DA1F2') # "darkgray" # "#292f33"
                            background_normal: "transparent"
                            background_down: "transparent"
                            disabled: False
                            opacity: 1
                            on_touch_down: root.copy_to_clipboard(newsCard4Post.type) if self.collide_point(*args[1].pos) else False
                            valign: 'top'
                            color: "white"
                            bold: False
                            font_size: 16 

                Label:
                    id: category5
                    size_hint_y: None
                    size_hint_x: None
                    height: 49
                    width: 730
                    text: ""
                    disabled: True
                    opacity: 1
                    halign: 'center'
                    color: "white"
                    bold: False,
                    opacity: 1
                    font_size: 16


#Screen 2: Add Profile
<AddProfileScreen>:
    bl1: boxLayout1
    ti1: profileName
    ti2: profileYoutube
    ti3: profileTwitter
    ti4: profileArticles
    ti5: profileSubreddit
    
    GridLayout:
        cols: 2
        rows: 1

        ScrollView:
            id: svScrollBar2
            do_scroll_x: False
            do_scroll_y: True
            effect_cls: 'ScrollEffect'
            size_hint_x: None
            width: 100

            BoxLayout:
                id: boxLayout1
                orientation: "vertical"
                size_hint_y: None
                height: self.minimum_height
                
                Button:
                    size_hint_y: None
                    text: "<"
                    on_press: root.manager.current = 'start'
                    font_size: 40
                    disabled: False
                    bold: True
                    background_color: "black"

        StackLayout:
            id: testStackLayout1
            size_hint_y: 1
            size_hint_x: 1
            
            Button:
                size_hint_y: None
                size_hint_x: 1
                height: 40
                # width: 730
                text: "Add Profile"
                background_color: 'green'
                background_normal: 'transparent'
                background_down: 'transparent'
                font_size: 22
                bold: True
                on_press: root.fetch_profile_inputs()
            TextInput:
                id: profileName
                size_hint_y: None
                size_hint_x: 1
                height: 40
                # width: 730
                font_size: 20
                hint_text: "profile name..."
                halign: "center"
                multiline: False
                write_tab: False
            TextInput:
                id: profileYoutube
                size_hint_y: None
                size_hint_x: 1
                height: 40
                # width: 730
                font_size: 20
                hint_text: "youtube channel name..."
                halign: "center"
                multiline: False
                write_tab: False
            TextInput:
                id: profileTwitter
                size_hint_y: None
                size_hint_x: 1
                height: 40
                # width: 730
                font_size: 20
                hint_text: "X username..."
                halign: "center"
                multiline: False
                write_tab: False
            TextInput:
                id: profileArticles
                size_hint_y: None
                size_hint_x: 1
                height: 40
                # width: 730
                font_size: 20
                hint_text: "articles search phrase..."
                halign: "center"
                multiline: False
                write_tab: False
            TextInput:
                id: profileSubreddit
                size_hint_y: None
                size_hint_x: 1
                height: 40
                # width: 730
                font_size: 20
                hint_text: "subreddit name..."
                halign: "center"
                multiline: False
                write_tab: False


#Screen 3: Remove Profile
<RemoveProfileScreen>:
    bl1: boxLayout1
    bl2: boxLayout2
    st1: testStackLayout1
    ti1: profileName
    btnRemoveProfile: removeProfileButton
    
    GridLayout:
        cols: 2
        rows: 1

        ScrollView:
            id: svScrollBar1
            do_scroll_x: False
            do_scroll_y: True
            effect_cls: 'ScrollEffect'
            size_hint_x: None
            width: 100

            BoxLayout:
                id: boxLayout1
                orientation: "vertical"
                size_hint_y: None
                height: self.minimum_height

                Button:
                    size_hint_y: None
                    text: "<"
                    on_press: root.manager.current = 'start'
                    font_size: 40
                    disabled: False
                    bold: True
                    background_color: "black"

        StackLayout:
            id: testStackLayout1
            size_hint_y: 1
            size_hint_x: 1

            TextInput:
                id: profileName
                size_hint_y: None
                size_hint_x: None
                height: 0
                font_size: 0
                hint_text: "Select Profile"
                halign: "center"
                disabled: True,
                multiline: False
                write_tab: False
            Button:
                id: removeProfileButton
                size_hint_y: None
                size_hint_x: 1
                height: 40
                background_color: 'red'
                background_normal: 'transparent'
                background_down: 'transparent'
                text: "Remove Profile"
                bold: True
                font_size: 22
                on_press: root.profile_delete()

            ScrollView:
                id: svScrollBar2
                do_scroll_x: False
                do_scroll_y: True
                effect_cls: 'ScrollEffect'
                size_hint_y: None
                size_hint_x: 1
                height: 580 # 440 + 80

                BoxLayout:
                    id: boxLayout2
                    orientation: 'vertical'
                    size_hint_y: None
                    height: self.minimum_height


#Screen 4: Favorites
<FavoritesScreen>:
    bl1: boxLayout1
    
    GridLayout:
        cols: 2
        rows: 1

        ScrollView:
            id: svScrollBar2
            do_scroll_x: False
            do_scroll_y: True
            effect_cls: 'ScrollEffect'
            size_hint_x: None
            width: 100

            BoxLayout:
                id: boxLayout1
                orientation: "vertical"
                size_hint_y: None
                height: self.minimum_height
                Button:
                    size_hint_y: None
                    text: "<"
                    on_press: root.manager.current = 'start'
                    font_size: 40
                    disabled: False
                    bold: True
                    background_color: "black"
        
        ScrollView:
            id: svScrollBar
            effect_cls: 'ScrollEffect'
            
            BoxLayout:
                id: boxLayoutPost
                orientation: 'vertical'
                size_hint_y: None
                height: self.minimum_height
                spacing: 10
                padding: 10


#Screen 5: Blank
<BlankScreen>: